apiVersion: v1
kind: Service
metadata:
  name: private-registry-nginx
  namespace: portal
spec:
  selector:
    app: pr-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
